services:
  postgres:
    image: postgres:11-alpine
    container_name: app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: app_redis
    environment:
      REDIS_ARGS: "--requirepass password --user app_username on >app_password ~* allcommands --user default off nopass nocommands"
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    command: server /data --console-address ":9001"
    volumes:
      - "minio-data:/data"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./mnt/postgres
      o: bind
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ./mnt/redis
      o: bind
  minio-data:
    driver: local
    driver_opts:
      type: none
      device: ./mnt/minio
      o: bind

networks:
  backend:
